feature [#559]: Task not serializable when using legacy HBase plugin
# New features and improvements

None.

# Breaking changes

None.

# Migration

None.

# Bug fixes

Fix Task not Serializable exception when writing using the HBase plugin.

```
2024-02-04 17:44:14.093 GMT+01:00 ERROR class=o.a.s.s.e.s.MicroBatchExecution application= node= Query pipegraph_CHPipegraph_structuredstreaming_Event_Storage_to_HBase_write
r_EventHBaseModel [id = 28a05189-b9b1-4e1e-b4cd-47173740ad04, runId = ef850577-c742-42de-84d4-122cd32dc1a2] terminated with error
org.apache.spark.SparkException: Task not serializable
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:416) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:406) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:163) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.SparkContext.clean(SparkContext.scala:2344) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:979) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:978) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:385) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:978) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.hadoop.hbase.spark.HBaseContext.bulkPut(HBaseContext.scala:138) ~[it.agilelab.wasp-plugin-hbase-spark_2.11-2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT.jar:2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT]
at org.apache.hadoop.hbase.spark.HBaseSink$$anonfun$addBatch$1.apply$mcV$sp(HBaseSink.scala:31) ~[it.agilelab.wasp-plugin-hbase-spark_2.11-2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT.jar:2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT]
        at org.apache.hadoop.hbase.spark.HBaseSink$$anonfun$addBatch$1.apply(HBaseSink.scala:31) ~[it.agilelab.wasp-plugin-hbase-spark_2.11-2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT.jar:2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT]
        at org.apache.hadoop.hbase.spark.HBaseSink$$anonfun$addBatch$1.apply(HBaseSink.scala:31) ~[it.agilelab.wasp-plugin-hbase-spark_2.11-2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT.jar:2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT]
        at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.hadoop.hbase.spark.HBaseSink.addBatch(HBaseSink.scala:29) ~[it.agilelab.wasp-plugin-hbase-spark_2.11-2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT.jar:2.32.0-558-cdp-release-is-affected-by-mavengate-cdp717-SNAPSHOT]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5$$anonfun$apply$17.apply(MicroBatchExecution.scala:540) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch$5.apply(MicroBatchExecution.scala:538) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.org$apache$spark$sql$execution$streaming$MicroBatchExecution$$runBatch(MicroBatchExecution.scala:537) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply$mcV$sp(MicroBatchExecution.scala:200) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1$$anonfun$apply$mcZ$sp$1.apply(MicroBatchExecution.scala:168) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.ProgressReporter$class.reportTimeTaken(ProgressReporter.scala:351) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:58) [org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution$$anonfun$runActivatedStream$1.apply$mcZ$sp(MicroBatchExecution.scala:168) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:56) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:162) ~[org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:281) [org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:193) [org.apache.spark.spark-sql_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
Caused by: java.io.NotSerializableException: org.apache.hadoop.conf.Configuration
Serialization stack:
        - object not serializable (class: org.apache.hadoop.conf.Configuration, value: Configuration: core-default.xml, core-site.xml, mapred-default.xml, mapred-site.xml, yarn-default.xml, yarn-site.xml, resource-types.xml, hdfs-default.xml, hdfs-site.xml, hbase-default.xml, hbase-site.xml, /etc/hbase/conf/hbase-site.xml)
        - field (class: org.apache.hadoop.hbase.spark.HBaseContext, name: config, type: class org.apache.hadoop.conf.Configuration)
        - object (class org.apache.hadoop.hbase.spark.HBaseContext, org.apache.hadoop.hbase.spark.HBaseContext@27799525)
        - field (class: org.apache.hadoop.hbase.spark.HBaseContext$$anonfun$bulkPut$1, name: $outer, type: class org.apache.hadoop.hbase.spark.HBaseContext)
        - object (class org.apache.hadoop.hbase.spark.HBaseContext$$anonfun$bulkPut$1, <function1>)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:413) ~[org.apache.spark.spark-core_2.11-2.4.7.7.1.7.0-551.jar:2.4.7.7.1.7.0-551]
        ... 35 more
```

# How this feature was tested

`HBaseContextSerializationSuite` + dependant project integration test.

# Related issue

Closes #559